In [193]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [194]:
df=pd.read_csv('brain_stroke.csv')
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
4976,Male,41.0,0,0,No,Private,Rural,70.15,29.8,formerly smoked,0
4977,Male,40.0,0,0,Yes,Private,Urban,191.15,31.1,smokes,0
4978,Female,45.0,1,0,Yes,Govt_job,Rural,95.02,31.8,smokes,0
4979,Male,40.0,0,0,Yes,Private,Rural,83.94,30.0,smokes,0
4980,Female,80.0,1,0,Yes,Private,Urban,83.75,29.1,never smoked,0

In [195]:
df.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             4981 non-null   object
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64
 3   heart_disease      4981 non-null   int64
 4   ever_married       4981 non-null   object
 5   work_type          4981 non-null   object
 6   Residence_type     4981 non-null   object
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object
 10  stroke             4981 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB

In [197]:
df['work_type'].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children'], dtype=object)

In [198]:
df[df['age']<1]

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
314,Female,0.64,0,0,No,children,Urban,83.82,24.9,Unknown,0
327,Female,0.88,0,0,No,children,Rural,88.11,15.5,Unknown,0
504,Female,0.32,0,0,No,children,Rural,73.71,16.2,Unknown,0
895,Male,0.88,0,0,No,children,Rural,157.57,19.2,Unknown,0
909,Male,0.24,0,0,No,children,Rural,118.87,16.3,Unknown,0
1003,Female,0.32,0,0,No,children,Rural,55.86,16.0,Unknown,0
1111,Female,0.72,0,0,No,children,Urban,66.36,23.0,Unknown,0
1212,Male,0.80,0,0,No,children,Rural,98.67,17.5,Unknown,0
1474,Male,0.40,0,0,No,children,Urban,109.56,14.3,Unknown,0
1487,Female,0.08,0,0,No,children,Urban,139.67,14.1,Unknown,0
1663,Female,0.64,0,0,No,children,Urban,62.27,17.3,Unknown,0
1821,Male,0.56,0,0,No,children,Rural,111.77,21.1,Unknown,0
1843,Male,0.24,0,0,No,children,Rural,146.97,18.5,Unknown,0
1852,Male,0.56,0,0,No,children,Rural,57.02,20.7,Unknown,0
1856,Male,0.64,0,0,No,children,Rural,86.74,16.2,Unknown,0
2178,Male,0.88,0,0,No,children,Urban,112.19,18.9,Unknown,0
2299,Male,0.88,0,0,No,children,Urban,90.62,22.4,Unknown,0
2308,Male,0.88,0,0,No,children,Urban,85.38,23.4,Unknown,0
2388,Male,0.32,0,0,No,children,Urban,127.78,20.8,Unknown,0
2437,Female,0.80,0,0,No,children,Urban,106.59,15.5,Unknown,0
2598,Male,0.80,0,0,No,children,Urban,75.22,33.1,Unknown,0
2666,Male,0.64,0,0,No,children,Urban,60.40,17.3,Unknown,0
2686,Male,0.24,0,0,No,children,Urban,58.35,18.6,Unknown,0
3013,Male,0.56,0,0,No,children,Rural,127.23,20.1,Unknown,0
3057,Male,0.08,0,0,No,children,Rural,70.33,16.9,Unknown,0
3148,Male,0.24,0,0,No,children,Urban,89.28,14.2,Unknown,0
3193,Male,0.56,0,0,No,children,Urban,98.23,14.1,Unknown,0
3363,Male,0.16,0,0,No,children,Urban,114.71,17.4,Unknown,0
3370,Male,0.80,0,0,No,children,Rural,114.54,15.1,Unknown,0
3592,Male,0.32,0,0,No,children,Urban,89.04,17.8,Unknown,0
3625,Female,0.56,0,0,No,children,Urban,80.92,18.3,Unknown,0
3728,Male,0.72,0,0,No,children,Rural,159.79,19.9,Unknown,0
3772,Female,0.48,0,0,No,children,Rural,118.75,17.4,Unknown,0
3996,Male,0.24,0,0,No,children,Urban,57.09,19.4,Unknown,0
4110,Female,0.72,0,0,No,children,Rural,112.19,20.1,Unknown,0
4276,Female,0.40,0,0,No,children,Rural,85.65,17.4,Unknown,0
4338,Female,0.48,0,0,No,children,Rural,94.06,14.8,Unknown,0
4592,Female,0.32,0,0,No,children,Urban,108.63,19.6,Unknown,0
4609,Male,0.72,0,0,No,children,Urban,80.08,16.4,Unknown,0
4762,Female,0.72,0,0,No,children,Rural,62.13,16.8,Unknown,0
4885,Male,0.48,0,0,No,children,Urban,73.02,17.9,Unknown,0

In [199]:
a=[]
for i in df['age']:
  if i<1:
    i=i*10
    a.append(i)
  else:
    a.append(i)

In [200]:
df['age']=a

In [201]:
df['age']=df['age'].astype(int)

In [202]:
df['age']=df['age'].replace(0,np.nan)

In [203]:
df.dropna(inplace=True)

In [204]:
df.drop('ever_married',axis=1,inplace=True)

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4979 entries, 0 to 4980
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             4979 non-null   object
 1   age                4979 non-null   float64
 2   hypertension       4979 non-null   int64
 3   heart_disease      4979 non-null   int64
 4   work_type          4979 non-null   object
 5   Residence_type     4979 non-null   object
 6   avg_glucose_level  4979 non-null   float64
 7   bmi                4979 non-null   float64
 8   smoking_status     4979 non-null   object
 9   stroke             4979 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 427.9+ KB

In [206]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['gender']=label.fit_transform(df['gender'])
df['work_type']=label.fit_transform(df['work_type'])
df['Residence_type']=label.fit_transform(df['Residence_type'])
df['smoking_status']=label.fit_transform(df['smoking_status'])

In [207]:
df.head()

,gender,age,hypertension,heart_disease,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.0,0,1,1,1,228.69,36.6,1,1
1,1,80.0,0,1,1,0,105.92,32.5,2,1
2,0,49.0,0,0,1,1,171.23,34.4,3,1
3,0,79.0,1,0,2,0,174.12,24.0,2,1
4,1,81.0,0,0,1,1,186.21,29.0,1,1

In [208]:
x=df.drop('stroke',axis=1)
y=df['stroke']

In [209]:
x

,gender,age,hypertension,heart_disease,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,1,67.0,0,1,1,1,228.69,36.6,1
1,1,80.0,0,1,1,0,105.92,32.5,2
2,0,49.0,0,0,1,1,171.23,34.4,3
3,0,79.0,1,0,2,0,174.12,24.0,2
4,1,81.0,0,0,1,1,186.21,29.0,1
...,...,...,...,...,...,...,...,...,...
4976,1,41.0,0,0,1,0,70.15,29.8,1
4977,1,40.0,0,0,1,1,191.15,31.1,3
4978,0,45.0,1,0,0,0,95.02,31.8,3
4979,1,40.0,0,0,1,0,83.94,30.0,3
4980,0,80.0,1,0,1,1,83.75,29.1,2

In [210]:
y

0       1
1       1
2       1
3       1
4       1
       ..
4976    0
4977    0
4978    0
4979    0
4980    0
Name: stroke, Length: 4979, dtype: int64

In [211]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [212]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)

0.9558232931726908

In [213]:
rf.predict([[0,45,1,0,0,0,95.02,31.8,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])

In [215]:
import pickle
file=open('brainstroke.pkl','wb')
pickle.dump(rf,file)

In [218]:
p=open('brainstroke.pkl','rb')
mod=pickle.load(p)

In [219]:
mod.predict([[0,45,1,0,0,0,95.02,31.8,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])